- frege/java/Util.fr
1.  Add methods to convert from Frege list to Java collection and from Java collection to Frege list.
2. Java methods that take an `Object` now take a generic type parameter so that we don't have to convert Frege values into Java objects
> Add java to frege and frege to java collection conversion methods

- frege/runtime/Concurrent.java
resolving issue #154 
tested with newly generated compiler to no longer conflict with synchronization on "".
No automated test case added.
> ForkJoin.par should not synchronize on "" #154

- doc/chapterdeclarations.tex
- doc/chaptermodules.tex
- frege/compiler/Typecheck.fr
Found a few small typos in the documentation.  (And one in a compiler error message.)
> fix a few small typos

- .travis.yml
- doc/chapterexpr.tex
- frege/compiler/grammar/Frege.fr
- frege/compiler/grammar/Frege.y
- frege/runtime/Phantom.java
- frege/tools/YYgen.fr
- tests/hcm/Lambda.fr
- tests/qc/PreludeProperties.fr
The following works now:
f = \a b -> (b,a)
The following is now a syntax error:
--      Frege: unexpected operator : while trying to parse lambda patterns
--      Haskell: parse error on input `:'
s = \x:xs -> xs 
And this is also used to work, but is now an error:
--      Frege: constructor Maybe.Just demands 1 arguments, but you gave 0
--      Haskell: Constructor `Just' should have 1 argument, but has been given none
j = \Just x -> x
> Implement Haskell Lambda Syntax

- frege/compiler/common/SymbolTable.fr
- frege/compiler/passes/Transdef.fr
- frege/prelude/PreludeBase.fr
- shadow/frege/java/util/Regex.fr
- shadow/frege/prelude/Math.fr
- shadow/frege/prelude/PreludeArrays.fr
- shadow/frege/prelude/PreludeBase.fr
- tests/hcm/Bool.fr
This contributes to Haskell compatibility.
The constructors True and False belong to a pseudo type HaskellBool, but are magically replaced in expressions and patterns with boolean literals true and false.
You can still define your own types with constructors `True` or `False` or use those words in types, type classes or modules.
> Support for True/False

- LICENSE.txt
I think this is the most safe thing to do: retain whole original license from Haskell libraries that are being ported and incorporated to Frege.
My experience from porting Ix and Arr is that more then 80% of code is just adaptation (parentheses, etc.). 
I also see that Frege is going to be more like Haskell (recently changed lambda expressions and type class instances). So another ports have chances to be even more like original Haskell code.
> Haskell code adapted and included to Frege requires Haskell license

- tests/qc/Ix.fr
In tests with pairs and triples two or three generators are used to increase probability of generating example satisfying assumptions.
`p_index_0_until_rangeSize_xxx` were not calling right property check.
> Ix QC generators changed to avoid too much discarded tests

- .gitignore
- .travis.yml
- Makefile
Fetching current fregec jar files from github.com, placing it in lib folder.
Generally using more GNU make features.
Building Java 6 version in build/build6;
Building Java 7 version in build/build7.
Building test files in build/test.
No explicit removing of temporary files and folder; they are removed with the targets clean and distclean.
> Removed unused variables, renamed remaining ones. Build all things in build/ and subfolders

- frege/StandardLibrary.fr
- frege/java/Lang.fr
- frege/system/Environment.fr
- shadow/frege/java/Lang.fr
- tests/qc/Environment.fr
`getArgs` is stubbed until Ingo rewrites how main is invoked.
`getProgName` is stubbed with no sensible result on the JVM.
`getEnv` throws IllegalArgumentException if the environment variable does not exist.
Added `newIAE` constructor to `IllegalArgumentException` until Ingo fixes the name lookup bug.
> Implement System.Environment to fix #227

- frege/prelude/PreludeText.fr
frege> show 'a'
'a'
frege> length (show 'a')
3
When in ghci:
Prelude A> showChar 'a' ""
"a"
Prelude A> length (showChar 'a' "")
1
> showChar should not add redundant quotes around character

- Makefile
- frege/compiler/gen/java/PrettyJava.fr
- tests/comp/Issue296.fr
The adaptation to the Makefile is optional, but is required for building the project on Windows/Cygwin.
> Fix for issue #296

- frege/data/Maybe.fr
@Ingo60 sorry again that i did not compile locally before send pull request since i though CI server will check the code.
and after compiled locally, i find some issues about #302 that i added a duplicate comma after `maybe` and broke the naming alias for `unJust` and `fromJust`, now it is cool and i also leave leading commas style alone as you mentioned.
> put back naming alias for Data.Maybe

- Makefile
when build locally on OSX, there is no format flag `-f` for the executable `/usr/bin/time`, so maybe it is better to auto detect `gnu-time` first.
> detect gnu-time

- frege/data/Char.fr
Relate to #230, add `isLetter` and `showLitChar `.
just leave alone `lexLitChar` and `readLitChar` for now because they are related to the lexer according to [here](https://github.com/ghc/ghc/blob/master/libraries/base/GHC/Read.hs#L52), so maybe next PR will work this out.
> review completeness and compatibility for Data.Char

- Makefile
This is a pull request to fix https://github.com/Frege/frege/issues/318 which seems less ad hoc than the fix suggested on the report.
Building with JDK9, TARGET=1.7 now builds a jar that is 1.7-clean, and that is compatible with the android build tools and works in my android app.
> Modify Makefile so TARGET=1.7 puts only 1.7 classes in the jar.

- README.md
The original link looks incorrect (returns 404.)
> Fix a link to the edX tutorial

- Makefile
`make runtime` produces 53.0 (JDK9) class files if compiled with javac from JDK9, which is incompatible with java from JDK8.
This PR makes sure that those classes are compiled in 52.0 (JDK8) by specifying `-source 1.8 -target 1.8`.
The other make targets don't need changes because they already have `-source` and `-target` options.
> Fix "make runtime" to respect TARGET

- frege/data/Foldable.fr
- frege/data/Traversable.fr
`Foldable` loses the superclass `Functor` and `Traversable` gains it as they do in Haskell.
Please see [this SO question of mine](https://stackoverflow.com/questions/47629536/why-does-foldable-inherit-from-functor-in-frege) for the conversation and examples.
This breaks existing instances of `Foldable` if it uses the ["All in one" instance declarations](https://github.com/Frege/frege/wiki/Differences-between-Frege-and-Haskell#all-in-one-instance-declarations) to define the members of `Functor`s.
> Remove the superclass Functor from Foldable

- frege/compiler/GenMeta.fr
- frege/compiler/common/Resolve.fr
- frege/compiler/passes/Imp.fr
- frege/compiler/types/Global.fr
- frege/tools/Doc.fr
Fixes #337 
This PR tries to fix the issue by populating `g.sub.packWhy` for used re-exported symbols.
> Fix #337: Avoid unnecessary "unused import" hint warnings for re-exported items

- frege/compiler/gen/java/Common.fr
- tests/comp/Issue284.fr
- tests/comp/Issue284a.fr
- tests/qc/Record.fr
Fixes #284 
This PR fixes #284 by mangling named fields of records type so that they have valid names in generated Java files.
`frege.compiler.gen.java.Common.namedFields` appears to be used in the following places:
- `frege.compiler.gen.java.Common.mkMember` for Java field declarations
- `frege.compiler.gen.java.DataCode.conDecls` for assignments in Java constructors
- `frege.compiler.gen.java.Match.match` for field accesses
At all of the places, name mangling is needed. This PR modifies `namedFields` itself to fix them all.
> Fix #284: Mangle named fields for Java

- Makefile
`make regression` re-compiles some classes for example `frege/runtime/Meta.class`.
Since in the `regression` target `-target` is not specified at fregec/javac, the classes are replaced with version 53.0 i.e. Java9 class files.
This commit avoids it by using a dedicated directory for the regression tests.
> Compile regression tests in a dedicated directory

- frege/compiler/Classtools.fr
- frege/compiler/Main.fr
- frege/compiler/common/CompilerOptions.fr
- frege/java/IO.fr
- frege/java/Util.fr
- frege/java/lang/Processes.fr
- frege/java/util/Jar.fr
- frege/java/util/Zip.fr
- frege/lib/Modules.fr
- frege/tools/Doc.fr
- frege/tools/MakeDocIndex.fr
- frege/tools/Quick.fr
- frege/tools/Splitter.fr
- frege/tools/YYgen.fr
- frege/tools/doc/Utilities.fr
- tests/comp/TDNR.fr
The native data type `java.IO.File` is now declared `pure native`.
Resolves #367
> Change the native type File to pure native

- frege/java/IO.fr
- frege/prelude/PreludeBase.fr
- frege/prelude/PreludeIO.fr
This PR mainly modifies `frege.java.IO` so that users can use it more comfortably.
- The following native types were changed to have `ST` members instead of `IO`s:
- Closeable
- Flushable
- Writer
- OutputStreamWriter
- PrintWriter
- StringWriter
- Reader
- InputStreamReader
- BufferedReader
The abstract super classes/interfaces don't necessarily do I/O. The prime example is `ByteArrayInputStream` (doesn't exist in the Frege library yet). Having super class members declared as `IO` forbids using such classes in semi-pure contexts, and users are forced to declare all of the needed native `ST` methods by their own.
Purity is preserved as long as values that do I/O is in `MutableIO`. All subclasses currently declared in the Frege library satisfy that (e.g. all of the constructors of …
> Change Input/OutputStream and "finally" to ST

- frege/prelude/PreludeArrays.fr
- tests/qc/PreludeArraysProp.fr
Resolves #366
- Changed:
- `JArray.genericFromList` now requires `JavaType` instead of `ArrayElement`
- `JArray.genericFromIndexList` now ignores negative indexes instead of throwing NPEs
- `JArray.genericModify` no longer requires `ArrayElement`
- `JArray.genericModify` now takes `(Maybe a -> Maybe a)`
- `JArray.genericFold` no longer requires `ArrayElement`
- `JArray.genericFold` now takes `(b -> Maybe a -> b)`
- Added:
- `JArray.genericModifyAt`
- `JArray.genericModifyElemAt`
- There is already `JArray.genericModify`, which modifies all of the elements in the array, but not one at a time.
These methods allow individual updates.
- `JArray.genericFromMaybeList`
- Found useful when writing the tests. Symmetric to `genericToMaybeList`.
- Requires `JavaType`.
- …
> Relax JArray constraints and add more consistent interface
